### ISSUE TITLE
Windows VST3 release request

### ISSUE THREAD

**Issue by vcvrackideas** [ffont/source#2]
Hi! very interesting project, I'm pretty weak in compiling plugins, could you make VST3 for windows please? Thanks in advance!

**Comment by ffont** [comment]
Hi, thanks for your comment. I'm not planning to do releases for different platforms for now as it is a bit time consuming, but building source as a VST plugin for windows should be relatively easy if you have a windows machine as it is a standard JUCE plugin. I'll consider in the future, when the plugin version of SOURCE is more advanced, to release releases for different platforms.
